printWidth: 80
tabWidth: 2
useTabs: true
semi: false
singleQuote: true
quoteProps: 'as-needed'
jsxSingleQuote: true
trailingComma: 'all'
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: 'always'
requirePragma: false
insertPragma: false
proseWrap: 'preserve'
htmlWhitespaceSensitivity: 'ignore'
vueIndentScriptAndStyle: false
embeddedLanguageFormatting: 'auto'
