/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./../src/components/demo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmployeeTagCard: typeof import('./../src/components/employeeTagCard/employeeTagCard.vue')['default']
    Loading: typeof import('./../src/components/loading/loading.vue')['default']
    NoResultYet: typeof import('./../src/components/noResultYet/noResultYet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/svgIcon/svgIcon.vue')['default']
    UserInfos: typeof import('./../src/components/userInfos/userInfos.vue')['default']
  }
}
